### ISSUE TITLE
数据集提取码错误

### ISSUE THREAD

**Issue by ZY-Zeng** [SSTato/Wall-crack-detection#2]
如题，m6h1的提取码提示错误。可以更新一下嘛

**Comment by ThanhPham1987** [comment]
yes, me too. I can not download. Would you like to update google drive?
Best regards,
PeterPham

**Comment by SSTato** [comment]
> 如题，m6h1的提取码提示错误。可以更新一下嘛

抱歉，由于是和其他公司合作的，所以暂时不能免费公开。

**Comment by SSTato** [comment]
> 抱歉，由于是和其他公司合作的，所以暂时不能免费公开。

Sorry, the dataset is a collaboration with other companies, so it is not free and public for now.
